<script setup>
import { computed, onMounted, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { apiClient } from "../../utils/api";
const loading=ref(false), rows=ref([]), people=ref([]), members=ref([]), selected=ref(null), createVisible=ref(false), memberVisible=ref(false), accountVisible=ref(false), pluginTokenStatus=ref({configured:false}), pluginTokenDialog=ref(false), pluginTokenValue=ref("");
const tenantForm=reactive({name:"",slug:"",owner_person_id:null}), memberForm=reactive({person_id:null,role:"member"}), accountForm=reactive({name:"",username:"",password:"",roles:["operator"]});
const planLabels={trial_1d:"1 天体验",trial_7d:"7 天体验",monthly:"月租",yearly:"年租"}, statusLabels={active:"已开通",trial:"体验中",expired:"已到期",suspended:"已暂停"};
const title=computed(()=>selected.value?.name||"企业详情");
async function load(){loading.value=true;try{const [tenants,users]=await Promise.all([apiClient.get("/api/tenants"),apiClient.get("/api/people")]);rows.value=tenants;people.value=users||[];if(selected.value){selected.value=rows.value.find(row=>row.id===selected.value.id)||null;if(selected.value)await Promise.all([loadMembers(),loadPluginTokenStatus()]);}}catch(error){ElMessage.error(error.message||"企业列表加载失败");}finally{loading.value=false;}}
async function loadMembers(){members.value=await apiClient.get(`/api/tenants/members?tenant_id=${selected.value.id}`)}
async function loadPluginTokenStatus(){pluginTokenStatus.value=await apiClient.get(`/api/tenants/plugin-token?tenant_id=${selected.value.id}`)}
async function open(row){selected.value=row;pluginTokenValue.value="";await Promise.all([loadMembers(),loadPluginTokenStatus()]);}
async function createTenant(){try{await apiClient.post("/api/tenants",tenantForm);ElMessage.success("企业已创建，默认开通 7 天体验");createVisible.value=false;Object.assign(tenantForm,{name:"",slug:"",owner_person_id:null});await load();}catch(error){ElMessage.error(error.message||"创建企业失败");}}
async function plan(code){try{await apiClient.post("/api/tenants/subscription",{tenant_id:selected.value.id,plan_code:code});ElMessage.success("授权已生效");await load();}catch(error){ElMessage.error(error.message||"授权失败");}}
async function suspend(){try{await ElMessageBox.confirm(`暂停后「${selected.value.name}」的成员将不能使用业务功能。确认继续吗？`,"暂停企业",{type:"warning",confirmButtonText:"确认暂停"});await apiClient.post("/api/tenants/subscription",{tenant_id:selected.value.id,subscription_status:"suspended"});ElMessage.success("企业已暂停");await load();}catch(error){if(error!=="cancel")ElMessage.error(error.message||"暂停失败");}}
async function saveMember(){try{await apiClient.put("/api/tenants/members",{tenant_id:selected.value.id,...memberForm,active:1});memberVisible.value=false;await loadMembers();await load();}catch(error){ElMessage.error(error.message||"保存成员失败");}}
async function remove(row){try{await ElMessageBox.confirm(`确认移除「${row.name}」吗？账号不会被删除。`,"移除成员",{type:"warning"});await apiClient.put("/api/tenants/members",{tenant_id:selected.value.id,person_id:row.person_id,role:row.role,active:0});await loadMembers();await load();}catch(error){if(error!=="cancel")ElMessage.error(error.message||"移除失败");}}
async function createAccount(){try{const person=await apiClient.post("/api/people",accountForm);memberForm.person_id=person.id||person.person_id;accountVisible.value=false;memberVisible.value=true;Object.assign(accountForm,{name:"",username:"",password:"",roles:["operator"]});await load();ElMessage.success("子账号已创建，请设置企业角色后保存");}catch(error){ElMessage.error(error.message||"创建子账号失败");}}
async function archive(){try{await ElMessageBox.confirm(`将归档「${selected.value.name}」，全部成员会被移出，但不直接删除业务数据。`,`归档企业`,{type:"error"});await apiClient.post("/api/tenants/archive",{tenant_id:selected.value.id});selected.value=null;members.value=[];await load();ElMessage.success("企业已归档");}catch(error){if(error!=="cancel")ElMessage.error(error.message||"归档失败");}}
async function issuePluginToken(){try{if(pluginTokenStatus.value.configured)await ElMessageBox.confirm("生成新令牌会立即撤销旧令牌，已配置旧令牌的插件需要重新粘贴。","重置企业插件令牌",{type:"warning"});const result=await apiClient.post("/api/tenants/plugin-token",{tenant_id:selected.value.id});pluginTokenValue.value=result.token;pluginTokenDialog.value=true;await loadPluginTokenStatus().catch(()=>{});}catch(error){if(error!=="cancel")ElMessage.error(error.message||"生成插件令牌失败");}}
async function revokePluginToken(){try{await ElMessageBox.confirm("撤销后，该企业所有已配置此令牌的浏览器插件将立即无法连接。","撤销企业插件令牌",{type:"warning"});await apiClient.delete(`/api/tenants/plugin-token?tenant_id=${selected.value.id}`);pluginTokenStatus.value={configured:false};ElMessage.success("插件令牌已撤销");}catch(error){if(error!=="cancel")ElMessage.error(error.message||"撤销插件令牌失败");}}
async function copyPluginToken(){try{await navigator.clipboard.writeText(pluginTokenValue.value);ElMessage.success("令牌已复制");}catch(error){ElMessage.error("复制失败，请手动选择并复制令牌");}}
onMounted(load);
</script>
<template>
  <main class="tenant-page" v-loading="loading">
    <header><div><h1>企业管理</h1><p>管理企业、成员账号、订阅权限与归档。</p></div><div><el-button @click="load">刷新</el-button><el-button type="primary" @click="createVisible=true">新增企业</el-button></div></header>
    <section class="workspace">
      <aside><strong>企业列表</strong><button v-for="row in rows" :key="row.id" :class="{active:selected?.id===row.id}" @click="open(row)"><b>{{row.name}}</b><small>{{planLabels[row.plan_code]||row.plan_code}} · {{row.member_count}} 人</small></button></aside>
      <section class="detail">
        <el-empty v-if="!selected" description="选择企业后管理成员、授权和归档" />
        <template v-else>
          <div class="detail-head"><div><h2>{{title}}</h2><span>{{selected.slug}} · {{statusLabels[selected.subscription_status]||selected.subscription_status}}</span></div><el-tag :type="selected.access_allowed?'success':'danger'">{{selected.access_allowed?'可使用':'不可使用'}}</el-tag></div>
          <el-descriptions :column="3" border><el-descriptions-item label="套餐">{{planLabels[selected.plan_code]||selected.plan_code}}</el-descriptions-item><el-descriptions-item label="到期">{{selected.subscription_expires_at||'长期有效'}}</el-descriptions-item><el-descriptions-item label="成员">{{selected.member_count}}</el-descriptions-item></el-descriptions>
          <section class="block"><h3>成员与子账号</h3><div class="block-actions"><el-button @click="memberVisible=true">加入现有用户</el-button><el-button type="primary" plain @click="accountVisible=true">创建子账号</el-button></div><el-table :data="members"><el-table-column prop="name" label="姓名" /><el-table-column prop="username" label="登录账号" /><el-table-column prop="role" label="企业角色" /><el-table-column label="操作" width="90"><template #default="{row}"><el-button link type="danger" :disabled="row.role==='owner'" @click="remove(row)">移除</el-button></template></el-table-column></el-table></section>
          <section class="block"><h3>套餐与授权</h3><div class="actions"><el-button @click="plan('trial_1d')">1 天体验</el-button><el-button @click="plan('trial_7d')">7 天体验</el-button><el-button type="primary" @click="plan('monthly')">月租</el-button><el-button type="primary" @click="plan('yearly')">年租</el-button><el-button type="danger" plain @click="suspend">暂停企业</el-button></div></section>
          <section class="block plugin-access"><div><h3>浏览器插件接入</h3><p>{{pluginTokenStatus.configured?'已配置企业专属令牌；重置会使旧令牌立即失效。':'尚未配置企业专属令牌。'}}</p><small>令牌仅在生成时显示一次，请粘贴到浏览器插件的“ERP 回传密钥”中。</small></div><div class="actions"><el-button type="primary" @click="issuePluginToken">{{pluginTokenStatus.configured?'重置令牌':'生成令牌'}}</el-button><el-button type="danger" plain :disabled="!pluginTokenStatus.configured" @click="revokePluginToken">撤销令牌</el-button></div></section>
          <section class="danger"><div><h3>危险操作</h3><p>归档会停用企业、移除成员，不直接删除业务数据。</p></div><el-button type="danger" @click="archive">归档企业</el-button></section>
        </template>
      </section>
    </section>
    <el-dialog v-model="createVisible" title="新增企业" width="460px"><el-form label-width="90px"><el-form-item label="企业名称"><el-input v-model="tenantForm.name" /></el-form-item><el-form-item label="企业标识"><el-input v-model="tenantForm.slug" placeholder="例如 acme-shop" /></el-form-item><el-form-item label="负责人"><el-select v-model="tenantForm.owner_person_id" clearable filterable><el-option v-for="person in people" :key="person.id" :label="`${person.name}（${person.username||'未设账号'}）`" :value="person.id" /></el-select></el-form-item></el-form><template #footer><el-button @click="createVisible=false">取消</el-button><el-button type="primary" @click="createTenant">创建</el-button></template></el-dialog>
    <el-dialog v-model="memberVisible" title="加入企业成员" width="460px"><el-form label-width="90px"><el-form-item label="用户"><el-select v-model="memberForm.person_id" filterable><el-option v-for="person in people" :key="person.id" :label="`${person.name}（${person.username||'未设账号'}）`" :value="person.id" /></el-select></el-form-item><el-form-item label="企业角色"><el-select v-model="memberForm.role"><el-option label="成员" value="member"/><el-option label="企业管理员" value="admin"/><el-option label="负责人" value="owner"/></el-select></el-form-item></el-form><template #footer><el-button @click="memberVisible=false">取消</el-button><el-button type="primary" @click="saveMember">保存</el-button></template></el-dialog>
    <el-dialog v-model="accountVisible" title="创建子账号" width="460px"><el-form label-width="90px"><el-form-item label="姓名"><el-input v-model="accountForm.name"/></el-form-item><el-form-item label="登录账号"><el-input v-model="accountForm.username"/></el-form-item><el-form-item label="初始密码"><el-input v-model="accountForm.password" show-password/></el-form-item></el-form><template #footer><el-button @click="accountVisible=false">取消</el-button><el-button type="primary" @click="createAccount">创建</el-button></template></el-dialog>
    <el-dialog v-model="pluginTokenDialog" title="企业插件令牌（仅显示一次）" width="620px"><p>请立即复制并粘贴到该企业用户的 Ozon 浏览器插件。关闭此窗口后无法再次查看；遗失时需重置令牌。</p><el-input v-model="pluginTokenValue" readonly /><template #footer><el-button @click="pluginTokenDialog=false">关闭</el-button><el-button type="primary" @click="copyPluginToken">复制令牌</el-button></template></el-dialog>
  </main>
</template>
<style scoped>
.tenant-page{padding:24px}.tenant-page header,.detail-head,.block-actions,.danger{display:flex;justify-content:space-between;gap:12px}.tenant-page h1,.detail h2,.block h3,.danger h3{margin:0}.tenant-page p,.detail-head span,.danger p{color:#64748b}.workspace{display:grid;grid-template-columns:260px 1fr;min-height:620px;border:1px solid #e5e7eb;border-radius:12px;overflow:hidden}.workspace aside{display:grid;align-content:start;gap:8px;padding:18px;border-right:1px solid #e5e7eb;background:#f8fafc}.workspace aside button{display:grid;gap:4px;padding:12px;border:0;border-radius:8px;background:transparent;text-align:left;cursor:pointer}.workspace aside button.active{background:#eaf2ff;color:#2563eb}.workspace aside small{color:#64748b}.detail{padding:24px}.detail-head{margin-bottom:18px}.block{margin-top:22px}.block h3{margin-bottom:10px}.block-actions{justify-content:flex-end;margin-bottom:10px}.actions{display:flex;flex-wrap:wrap;gap:10px}.danger{margin-top:24px;padding:16px;border:1px solid #fecaca;border-radius:10px;background:#fff7f7}.plugin-access{align-items:center;padding:16px;border:1px solid #dbeafe;border-radius:10px;background:#f8fbff}.plugin-access p{margin:8px 0}.plugin-access small{color:#64748b}
@media(max-width:760px){.workspace{grid-template-columns:1fr}.workspace aside{border-right:0;border-bottom:1px solid #e5e7eb}.detail{padding:16px}.plugin-access{align-items:flex-start;flex-direction:column}}
</style>
